version: 2

models:
  - name: user_random_numbers
    config:
      submission_method: job_cluster
      job_cluster_config:
        spark_version: 13.3.x-cpu-ml-scala2.12
        node_type_id: Standard_DS3_v2
        num_workers: 1
    description: customers with random numbers
    columns:
      - name: id
        description: the primary key for this table
        tests:
          - unique
          - not_null
      - name: user_random_number
        description: score
        tests:
          - not_null
