 jaffle_shop:
   target: sql_warehouse
   outputs:
     all_purpose:
      type: databricks
      schema: "lr_dbt_tests"
      host: "adb-984752964297111.11.azuredatabricks.net"
      http_path: "sql/protocolv1/o/984752964297111/0812-165614-tibia842"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
     sql_warehouse:
      type: databricks
      schema: "lr_dbt_tests"
      host: "adb-984752964297111.11.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/2e78d4a8647e3893"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
     spark_localhost:
      type: spark
      schema: "lr_dbt_tests"
      host: localhost
      method: session
      threads: 2
